#!/usr/bin/env sh
mkdir -p ~/.ethereum ~/.web3

# check if sudo is necessary
if ! id -nG $(whoami)|grep -qw "docker"; then SUDO='sudo'; else SUDO=''; fi

$SUDO docker run --rm -it \
           -p 127.0.0.1:8811:8811 \
           -p 0.0.0.0:20203:20203 \
           -v ~/.ethereum:/.ethereum \
           -v ~/.web3:/.web3 \
           -e HOME=/ \
           --user $(id -u):$(id -g) \
           ethereum/client-cpp $@

